/**
 * MFE Bootstrap
 *
 * Registers MFE domains, extensions, and handlers with the FrontX app.
 * Initial screen mounting is owned by ExtensionDomainSlot once its container
 * ref is attached.
 * This file is imported in main.tsx to wire MFE capabilities into the host app.
 *
 * MFE manifests are auto-generated by the `generate:mfe-manifests` script into
 * ./generated-mfe-manifests. Re-run it after adding or removing MFE packages
 * from src/mfe_packages/ with your package manager, for example
 * `npm run generate:mfe-manifests`, `yarn generate:mfe-manifests`, or
 * `pnpm generate:mfe-manifests`.
 */

import type { RefObject } from 'react';
import type { HAI3App, Extension, ScreenExtension } from '@cyberfabric/react';
import { bootstrapMfeDomains } from '@cyberfabric/react';
import { MFE_MANIFESTS, type MfeManifestConfig } from './generated-mfe-manifests.ts';

function isScreenExtension(extension: Extension): extension is ScreenExtension {
  const candidate = extension as { presentation?: { route?: string } };
  return typeof candidate.presentation?.route === 'string';
}

/**
 * Bootstrap MFE system for the host application.
 * Registers domains, extensions, and shared properties.
 * Initial screen mount is deferred to MfeScreenContainer -> ExtensionDomainSlot.
 *
 * @param app - FrontX application instance
 * @param screenContainerRef - React ref for the screen domain container element
 * @returns Array of registered screen extensions, for URL routing in MfeScreenContainer
 */
export async function bootstrapMFE(
  app: HAI3App,
  screenContainerRef: RefObject<HTMLDivElement | null>,
): Promise<ScreenExtension[]> {
  const screensetsRegistry = await bootstrapMfeDomains(app, screenContainerRef);

  if (MFE_MANIFESTS.length === 0) {
    console.warn(
      '[MFE Bootstrap] No MFE manifests found. From the project root, run `generate:mfe-manifests` with your package manager, for example `npm run generate:mfe-manifests`, `yarn generate:mfe-manifests`, or `pnpm generate:mfe-manifests`.',
    );
    return [];
  }

  const manifests = MFE_MANIFESTS as MfeManifestConfig[];
  const screenExtensions: ScreenExtension[] = [];

  for (const config of manifests) {
    // Register MFE-carried schemas (custom actions, properties) before entries so the
    // type system can validate entry references to these schemas at registration time.
    if (config.schemas) {
      for (const schema of config.schemas) {
        screensetsRegistry.typeSystem.registerSchema(schema);
      }
    }

    screensetsRegistry.typeSystem.register(config.manifest);

    for (const entry of config.entries) {
      screensetsRegistry.typeSystem.register({ ...entry, manifest: config.manifest });
    }

    for (const extension of config.extensions) {
      await screensetsRegistry.registerExtension(extension);
    }

    screenExtensions.push(...config.extensions.filter(isScreenExtension));
  }

  if (screenExtensions.length === 0) {
    console.warn('[MFE Bootstrap] No screen extensions available, skipping mount');
    return [];
  }

  return screenExtensions;
}
