// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

import type { Extension, JSONSchema, MfeEntry } from '@cyberfabric/react';

export interface MfeManifestConfig {
  manifest: JSONSchema;
  entries: MfeEntry[];
  extensions: Extension[];
  /** MFE-carried schemas (custom actions, properties). Registered before entries and extensions. */
  schemas?: JSONSchema[];
}

export const MFE_MANIFESTS: MfeManifestConfig[] = [

];

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
